language: objective-c
osx_image: xcode7.2
xcode_project: travis-ci-ssl-playground.xcodeproj
xcode_scheme: travis-ci-ssl-playground
xcode_sdk: iphonesimulator
matrix:
  include:
    - osx_image: xcode7.1
    - osx_image: xcode7
script:
  - xctool -project travis-ci-ssl-playground.xcodeproj -scheme travis-ci-ssl-playground -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6' build test
